### ISSUE TITLE
Could not execute entrypoint stage 'client' due to errors, provided by 'vs_eureka'!

### ISSUE THREAD

**Issue by gooma98** [ValkyrienSkies/Eureka#112]
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'vs_eureka'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ExceptionInInitializerError
	at org.valkyrienskies.eureka.fabric.EurekaModFabric$Client.onInitializeClient(EurekaModFabric.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 15 more
Caused by: java.lang.IllegalArgumentException: 
	at me.jellysquid.mods.lithium.common.state.StatePropertyTableCache.getTableCache(StatePropertyTableCache.java:34)
	at net.minecraft.class_2688.handler$cpp000$postCreateWithTable(class_2688.java:528)
	at net.minecraft.class_2688.method_28496(class_2688.java:147)
	at net.minecraft.class_2689.<init>(class_2689.java:68)
	at org.valkyrienskies.eureka.blockentity.renderer.WheelModels$definition$1.<init>(WheelModels.java:26)
	at org.valkyrienskies.eureka.blockentity.renderer.WheelModels.<clinit>(WheelModels.java:26)
	... 17 more

I use create , tech reborn

**Comment by Rubydesic** [comment]
Lithium incompatible
