### ISSUE TITLE
Game crashes when attempting to disassemble ship 1.20.1

### ISSUE THREAD

**Issue by GrayTrys** [ValkyrienSkies/Eureka#232]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [x] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.1

### Mod Loader

Forge

### Issue description

The ship wont disassemble and the game will crash in 1.20.1

The game crashed whilst ticking block entity
Error: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 24

### Issue reproduction

disassemble ship in 1.20.1

### Logs

[15:38:29] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:897) ~[client-1.20.1-20230612.114412-srg.jar%23348!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23348!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23348!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23348!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23348!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 24
	at net.minecraft.world.level.chunk.ChunkAccess.m_183278_(ChunkAccess.java:156) ~[client-1.20.1-20230612.114412-srg.jar%23348!/:?]
	at net.minecraft.world.level.chunk.LevelChunk.m_6978_(LevelChunk.java:215) ~[client-1.20.1-20230612.114412-srg.jar%23348!/:?]
	at org.valkyrienskies.mod.util.RelocationUtilKt.relocateBlock(RelocationUtilKt.java:51) ~[valkyrienskies-1201-2.3.0-beta.3.jar%23341!/:?]
	at org.valkyrienskies.mod.util.RelocationUtilKt.relocateBlock(RelocationUtilKt.java:110) ~[valkyrienskies-1201-2.3.0-beta.3.jar%23341!/:?]
	at org.valkyrienskies.eureka.util.ShipAssembler.unfillShip$lambda$5(ShipAssembler.java:129) ~[eureka-1201-1.3.0-beta.1.jar%23283!/:?]
	at org.valkyrienskies.core.impl.chunk_tracking.ShipActiveChunksSet.forEach(ShipActiveChunksSet.kt:49) ~[valkyrienskies-1201-2.3.0-beta.3.jar%23341!/:?]
	at org.valkyrienskies.eureka.util.ShipAssembler.unfillShip(ShipAssembler.java:109) ~[eureka-1201-1.3.0-beta.1.jar%23283!/:?]
	at org.valkyrienskies.eureka.blockentity.ShipHelmBlockEntity.disassemble(ShipHelmBlockEntity.java:122) ~[eureka-1201-1.3.0-beta.1.jar%23283!/:?]
	at org.valkyrienskies.eureka.blockentity.ShipHelmBlockEntity.tick(ShipHelmBlockEntity.java:90) ~[eureka-1201-1.3.0-beta.1.jar%23283!/:?]
	at org.valkyrienskies.eureka.block.ShipHelmBlock.getTicker$lambda$1(ShipHelmBlock.java:139) ~[eureka-1201-1.3.0-beta.1.jar%23283!/:?]
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:689) ~[client-1.20.1-20230612.114412-srg.jar%23348!/:?]
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:782) ~[client-1.20.1-20230612.114412-srg.jar%23348!/:?]
	at net.minecraft.world.level.Level.m_46463_(Level.java:468) ~[client-1.20.1-20230612.114412-srg.jar%23348!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:351) ~[client-1.20.1-20230612.114412-srg.jar%23348!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%23348!/:?]
	... 5 more
[15:38:29] [Server thread/FATAL]: Preparing crash report with UUID 63dcb261-40b9-40a4-ba0e-48f0c9f96e94
[15:38:29] [Server thread/ERROR]: This crash report has been saved to: C:\Users\Graysoncode\curseforge\minecraft\Instances\MaD\crash-reports\crash-2023-07-17_15.38.29-server.txt
[15:38:29] [Server thread/INFO]: Stopping server
[15:38:29] [Server thread/INFO]: Saving players
[15:38:29] [Render thread/FATAL]: Preparing crash report with UUID e8891a2c-90c8-4cac-849a-5779792242ed

**Comment by Tursiops-G** [comment]
Can you re-join the world after restart, or is the world Bricked?

**Comment by erazare** [comment]
just in case this is of interest to the developer, while i have experienced this as well, it does NOT crash the server, it crashes client
if that helps.. i hope it does.

**Comment by GrayTrys** [comment]
The world still works after crash but the boat doesn't dissasemble

**Comment by OneLoneFox** [comment]
I can confirm this issue, the world isn't corrupted but the ship behaves weirdly after the crash, it is unable to turn and trying to disassemble again instead (sometimes) fixes the turning and crashes in the next disassembly attempt (I've got the same crash report) 

https://github.com/ValkyrienSkies/Eureka/assets/28937206/a480829a-d675-44de-a12b-4f42656a2cbd

**Comment by CryingSurrogate** [comment]
Can confirm this still being an issue

**Comment by Bannta** [comment]
"Hello, I noticed this issue appears to be in the new Forge release. I experienced this in the 47.2.x version and even the 47.1.47. In 47.1.43 I can successfully disassemble my ship. However, vessels assembled above .43 don't want to disassemble. I have not tested this on .44, .45, and or .46 forge release versions. I hope this helps you guys out.  Regards,"
-Sorry, it stopped working very quickly afterward 

-side note, I do lose the Wheel graphic on my helm, but it still functions, just the stump part helm is visible, (probably another issue I need to look for that might be causing it.

**Comment by PriestOfFern** [comment]
Known issue, disassembly on non 1.18 versions is known to be buggy. Those versions just aren’t maintained as much

**Comment by dangerousones** [comment]
I also have this issue

**Comment by Gohirro** [comment]
Same, using Forge 47.2.1 Mod version eureka-1201-1.3.0-beta.2, valkyrienskies-1201-2.3.0-beta.4. Disassemble crashes server and does not work.

**Comment by millennIumAMbiguity** [comment]
Does this issues still persist in newer eureka versions?

**Comment by FoxyFox909** [comment]
I confirm it still persists in 1.20.1

**Comment by Naireem-sudo** [comment]
Can confirm on 1.20.1 FABRIC.
