### ISSUE TITLE
Exploding TNT near ship helm causes crash

### ISSUE THREAD

**Issue by copperwarrior** [ValkyrienSkies/Eureka#25]
```
java.lang.NullPointerException: null cannot be cast to non-null type org.valkyrienskies.core.api.ShipForcesInducer
	at org.valkyrienskies.core.game.ships.ShipObjectServer.applyAttachmentInterfaces(ShipObjectServer.kt:55)
	at org.valkyrienskies.core.game.ships.ShipObjectServer.saveAttachment(ShipObjectServer.kt:48)
	at org.valkyrienskies.eureka.block.ShipHelmBlock.onRemove(ShipHelmBlock.java:136)
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.onRemove(BlockBehaviour.java:870)
	at net.minecraft.world.level.chunk.LevelChunk.setBlockState(LevelChunk.java:276)
	at net.minecraft.world.level.Level.setBlock(Level.java:231)
	at net.minecraft.world.level.Level.setBlock(Level.java:217)
	at net.minecraft.world.level.Explosion.finalizeExplosion(Explosion.java:283)
	at net.minecraft.server.level.ServerLevel.explode(ServerLevel.java:1032)
	at net.minecraft.world.level.Level.explode(Level.java:573)
	at net.minecraft.world.entity.item.PrimedTnt.explode(PrimedTnt.java:100)
	at net.minecraft.world.entity.item.PrimedTnt.tick(PrimedTnt.java:88)
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:621)
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:561)
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:411)
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:811)
	at net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:91)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Tested on latest Eureka on Fabric.

**Comment by Rubydesic** [comment]
fixed in vs-core c8b2b0cc962edc02cf7289f98750c1d3638deb79
