### ISSUE TITLE
Game crash when launched

### ISSUE THREAD

**Issue by FewerElk** [ValkyrienSkies/Eureka#259]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20​

### Mod Loader

Forge

### Issue description

When I launch my game with eureka and valkiriens skies it crash.

### Issue reproduction

Launch your 1.20 forge minecraft
see crash

### Logs
[11oct.2023 14:20:05.149] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, FewerElk3623281, --version, 1.20.1-forge-47.1.0, --gameDir, C:\Users\*****\AppData\Roaming\.minecraft, --assetsDir, C:\Users\*****\AppData\Roaming\.minecraft\assets, --assetIndex, 5, --uuid, 35549300bf68481fa5fce85b584b641f, --accessToken, ????????, --clientId, ZTU5OWQ5ZDktNWNjNi00YzFhLTg4ZTctNWFkYWM1ZmMzOTg0, --xuid, 2535411763379785, --userType, msa, --versionType, release, --quickPlayPath, C:\Users\*****\AppData\Roaming\.minecraft\quickPlay\java\1697026801786.json, --launchTarget, forgeclient, --fml.forgeVersion, 47.1.0, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412]
[11oct.2023 14:20:05.164] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.8 by Microsoft; OS Windows 11 arch amd64 version 10.0
[11oct.2023 14:20:05.466] [main/INFO] [net.minecraftforge.fml.loading.ImmediateWindowHandler/]: Loading ImmediateWindowProvider fmlearlywindow
[11oct.2023 14:20:05.677] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.6
[11oct.2023 14:20:06.111] [main/INFO] [EARLYDISPLAY/]: Requested GL version 4.6 got version 4.6
[11oct.2023 14:20:06.343] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/*****/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%23100!/ Service=ModLauncher Env=CLIENT
[11oct.2023 14:20:06.383] [pool-2-thread-1/INFO] [EARLYDISPLAY/]: GL info: AMD Radeon(TM) Graphics GL version 4.6.14761 Core Profile Forward-Compatible Context 21.30.40.09 30.0.13040.9001, ATI Technologies Inc.
[11oct.2023 14:20:06.811] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\*****\AppData\Roaming\.minecraft\libraries\net\minecraftforge\fmlcore\1.20.1-47.1.0\fmlcore-1.20.1-47.1.0.jar is missing mods.toml file
[11oct.2023 14:20:06.881] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\*****\AppData\Roaming\.minecraft\libraries\net\minecraftforge\javafmllanguage\1.20.1-47.1.0\javafmllanguage-1.20.1-47.1.0.jar is missing mods.toml file
[11oct.2023 14:20:06.919] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\*****\AppData\Roaming\.minecraft\libraries\net\minecraftforge\lowcodelanguage\1.20.1-47.1.0\lowcodelanguage-1.20.1-47.1.0.jar is missing mods.toml file
[11oct.2023 14:20:06.952] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users*****\AppData\Roaming\.minecraft\libraries\net\minecraftforge\mclanguage\1.20.1-47.1.0\mclanguage-1.20.1-47.1.0.jar is missing mods.toml file
[11oct.2023 14:20:07.627] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: Found 22 dependencies adding them to mods collection
[11oct.2023 14:20:09.534] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[11oct.2023 14:20:09.563] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.20.1-forge-47.1.0, --gameDir, C:\Users\*****\AppData\Roaming\.minecraft, --assetsDir, C:\Users\*****\AppData\Roaming\.minecraft\assets, --uuid, 35549300bf68481fa5fce85b584b641f, --username, FewerElk3623281, --assetIndex, 5, --accessToken, ????????, --clientId, ZTU5OWQ5ZDktNWNjNi00YzFhLTg4ZTctNWFkYWM1ZmMzOTg0, --xuid, 2535411763379785, --userType, msa, --versionType, release, --quickPlayPath, C:\Users\*****\AppData\Roaming\.minecraft\quickPlay\java\1697026801786.json]
[11oct.2023 14:20:09.701] [main/WARN] [mixin/]: Reference map 'eureka-1201-forge-refmap.json' for vs_eureka.mixins.json could not be read. If this is a development environment you can ignore this message
[11oct.2023 14:20:10.806] [main/WARN] [mixin/]: Error loading class: com/jozufozu/flywheel/backend/instancing/instancing/InstancingEngine (java.lang.ClassNotFoundException: com.jozufozu.flywheel.backend.instancing.instancing.InstancingEngine)
[11oct.2023 14:20:10.810] [main/WARN] [mixin/]: Error loading class: com/jozufozu/flywheel/backend/instancing/blockentity/BlockEntityInstanceManager (java.lang.ClassNotFoundException: com.jozufozu.flywheel.backend.instancing.blockentity.BlockEntityInstanceManager)
[11oct.2023 14:20:10.812] [main/WARN] [mixin/]: Error loading class: com/jozufozu/flywheel/backend/instancing/InstanceManager (java.lang.ClassNotFoundException: com.jozufozu.flywheel.backend.instancing.InstanceManager)
[11oct.2023 14:20:10.815] [main/WARN] [mixin/]: Error loading class: com/jozufozu/flywheel/backend/instancing/InstanceWorld (java.lang.ClassNotFoundException: com.jozufozu.flywheel.backend.instancing.InstanceWorld)
[11oct.2023 14:20:10.817] [main/WARN] [mixin/]: Error loading class: com/jozufozu/flywheel/backend/instancing/instancing/InstancingEngine (java.lang.ClassNotFoundException: com.jozufozu.flywheel.backend.instancing.instancing.InstancingEngine)
[11oct.2023 14:20:10.819] [main/WARN] [mixin/]: Error loading class: com/sonicether/soundphysics/SoundPhysics (java.lang.ClassNotFoundException: com.sonicether.soundphysics.SoundPhysics)
[11oct.2023 14:20:10.832] [main/WARN] [mixin/]: Error loading class: blusunrize/immersiveengineering/common/gui/BlockEntityInventory (java.lang.ClassNotFoundException: blusunrize.immersiveengineering.common.gui.BlockEntityInventory)
[11oct.2023 14:20:10.834] [main/WARN] [mixin/]: Error loading class: cofh/core/block/entity/TileCoFH (java.lang.ClassNotFoundException: cofh.core.block.entity.TileCoFH)
[11oct.2023 14:20:10.848] [main/WARN] [mixin/]: Error loading class: me/jellysquid/mods/sodium/client/render/chunk/RenderSectionManager (java.lang.ClassNotFoundException: me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager)
[11oct.2023 14:20:10.849] [main/WARN] [mixin/]: @Mixin target me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager was not found valkyrienskies-forge.mixins.json:compat.sodium.MixinRenderSectionManager
[11oct.2023 14:20:10.879] [main/ERROR] [mixin/]: valkyrienskies-common.mixins.json:feature.container_distance_check.MixinContainer: Interface mixin contains a non-public method! Found includeShipsInDistanceCheck(Lnet/minecraft/world/entity/player/Player;DDD)D in valkyrienskies-common.mixins.json:feature.container_distance_check.MixinContainer
org.spongepowered.asm.mixin.transformer.throwables.InvalidInterfaceMixinException: Interface mixin contains a non-public method! Found includeShipsInDistanceCheck(Lnet/minecraft/world/entity/player/Player;DDD)D in valkyrienskies-common.mixins.json:feature.container_distance_check.MixinContainer
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorInterface.prepareMethod(MixinPreProcessorInterface.java:65) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.prepare(MixinPreProcessorStandard.java:187) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo$State.validate(MixinInfo.java:322) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.validate(MixinInfo.java:913) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:801) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:567) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.9.jar:10.0.9+10.0.9+main.dcd20f30]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:637) ~[?:?]
	at java.lang.Class.forName(Class.java:545) ~[?:?]
	at net.minecraftforge.fml.earlydisplay.DisplayWindow.lambda$updateModuleReads$18(DisplayWindow.java:586) ~[fmlearlydisplay-1.20.1-47.1.0.jar:1.0]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraftforge.fml.earlydisplay.DisplayWindow.updateModuleReads(DisplayWindow.java:586) ~[fmlearlydisplay-1.20.1-47.1.0.jar:1.0]
	at net.minecraftforge.fml.loading.ImmediateWindowHandler.acceptGameLayer(ImmediateWindowHandler.java:71) ~[fmlloader-1.20.1-47.1.0.jar:1.0]
	at net.minecraftforge.fml.loading.FMLLoader.beforeStart(FMLLoader.java:207) ~[fmlloader-1.20.1-47.1.0.jar:1.0]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.launchService(CommonLaunchHandler.java:92) ~[fmlloader-1.20.1-47.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
[11oct.2023 14:20:16.680] [pool-4-thread-1/WARN] [mixin/]: Error loading class: kotlin/Pair (java.lang.ClassNotFoundException: kotlin.Pair)

**Comment by millennIumAMbiguity** [comment]
try a different Kotlin version.

**Comment by FewerElk** [comment]
What is that ?

**Comment by millennIumAMbiguity** [comment]
Kotlin for Forge
