### ISSUE TITLE
Fabric 1.20.1 - Accidentally adding the same item stack twice [Anchor] to a Creative Mode Tab: Eureka

### ISSUE THREAD

**Issue by GameBurrow** [ValkyrienSkies/Eureka#288]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue ~~and it occurs when no other mods are installed~~

### Minecraft Version

1.20​

### Mod Loader

Fabric

### Issue description

Causes both the server and client to ccrash on right after world has loaded with the following error:

```
java.lang.IllegalStateException: Accidentally adding the same item stack twice [Anchor] to a Creative Mode Tab: Eureka
	at net.minecraft.class_1761$class_7703.method_45417(class_1761.java:252)
	at net.minecraft.class_1761$class_7704.method_45421(class_1761.java:286)
	at org.valkyrienskies.eureka.registry.CreativeTabs.create$lambda$3(CreativeTabs.java:19)
	at net.minecraft.class_1761.method_47306(class_1761.java:101)
	at net.minecraft.class_1761.polymer$getContentsWith(class_1761.java:3044)
	at eu.pb4.polymer.core.api.item.PolymerItemGroupUtils.getContentsFor(PolymerItemGroupUtils.java:37)
	at eu.pb4.universalshops.gui.setup.SelectItemGui.updateCachedItems(SelectItemGui.java:109)
	at eu.pb4.universalshops.UniversalShopsMod.lambda$onInitialize$0(UniversalShopsMod.java:38)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:49)
	at net.minecraft.server.MinecraftServer.handler$eba000$fabric-lifecycle-events-v1$afterSetupServer(MinecraftServer.java:8842)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Issue reproduction

1. Create modpack with Fabric 1.14.25
2. Add Eureka and VS2 mods
3. Add Roughly Enough items
4. Create a Singleplayer world

### Logs

**Issue produced on server:**

[crash-2024-01-01_18.49.34-server.txt](https://github.com/ValkyrienSkies/Eureka/files/13805609/crash-2024-01-01_18.49.34-server.txt)
[latest.log](https://github.com/ValkyrienSkies/Eureka/files/13805615/latest.log)

**Issue produced on client world:**
[crash-2024-01-01_20.52.18-server.txt](https://github.com/ValkyrienSkies/Eureka/files/13805616/crash-2024-01-01_20.52.18-server.txt)
[latest.log](https://github.com/ValkyrienSkies/Eureka/files/13805617/latest.log)

**Comment by GameBurrow** [comment]
Did some extra testing.

# Test 1
> Only  Eureka & Valkyrien Skyes is installed - No issues

When Only Eureka & Valkyrien Skyes is installed, it appears the game doesn't crash (used same MC and Fabric version) and error does not occur.

# Test 2
> Our modpack but without Universal shops - No crash but similar error still there

Noticed in the crash log `pb4.universalshops` so tried our modpack without that mod. The server does not crash, but similar error still occurs, this time by REI:
```
[REI-ReloadPlugins/ERROR]: [REI] Failed to collect creative tab: net.minecraft.class_1761@5d0faa61
java.lang.IllegalStateException: Accidentally adding the same item stack twice [Anchor] to a Creative Mode Tab: Eureka
	at net.minecraft.class_1761$class_7703.method_45417(class_1761.java:252) ~[client-intermediary.jar:?]
	at net.minecraft.class_1761$class_7704.method_45421(class_1761.java:286) ~[client-intermediary.jar:?]
	at org.valkyrienskies.eureka.registry.CreativeTabs.create$lambda$3(CreativeTabs.java:19) ~[eureka-1201-1.3.0-beta.3.jar:?]
	at me.shedaniel.rei.impl.client.fabric.CreativeModeTabCollectorImpl.collectTabs(CreativeModeTabCollectorImpl.java:56) ~[RoughlyEnoughItems-12.0.684-fabric.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at me.shedaniel.rei.plugin.client.DefaultClientPlugin.collectTabs(DefaultClientPlugin.java:174) ~[RoughlyEnoughItems-12.0.684-fabric.jar:?]
	at me.shedaniel.rei.plugin.client.DefaultClientPlugin.registerEntries(DefaultClientPlugin.java:135) ~[RoughlyEnoughItems-12.0.684-fabric.jar:?]
	at me.shedaniel.rei.impl.common.entry.type.EntryRegistryImpl.acceptPlugin(EntryRegistryImpl.java:69) ~[RoughlyEnoughItems-12.0.684-fabric.jar:?]
	at me.shedaniel.rei.impl.common.entry.type.EntryRegistryImpl.acceptPlugin(EntryRegistryImpl.java:51) ~[RoughlyEnoughItems-12.0.684-fabric.jar:?]
	at me.shedaniel.rei.api.common.registry.Reloadable.acceptPlugin(Reloadable.java:78) ~[RoughlyEnoughItems-12.0.684-fabric.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$startReload$9(PluginManagerImpl.java:417) ~[RoughlyEnoughItems-12.0.684-fabric.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$pluginSection$4(PluginManagerImpl.java:199) ~[RoughlyEnoughItems-12.0.684-fabric.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$startReload$10(PluginManagerImpl.java:407) ~[RoughlyEnoughItems-12.0.684-fabric.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.pluginSection(PluginManagerImpl.java:197) ~[RoughlyEnoughItems-12.0.684-fabric.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.startReload(PluginManagerImpl.java:405) ~[RoughlyEnoughItems-12.0.684-fabric.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCore._reloadPlugins(RoughlyEnoughItemsCore.java:162) ~[RoughlyEnoughItems-12.0.684-fabric.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$reloadPlugins$25(RoughlyEnoughItemsCoreClient.java:485) ~[RoughlyEnoughItems-12.0.684-fabric.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

# Test 3
> Only  Eureka & Valkyrien Skyes & REI

Combining info from all other errors, tried only Eureka & VS with REI and the error occurs again:
```
[22:26:36] [REI-ReloadPlugins/ERROR]: [REI] Failed to collect creative tab: net.minecraft.class_1761@1ba2cf37
java.lang.IllegalStateException: Accidentally adding the same item stack twice [Anchor] to a Creative Mode Tab: Eureka
	at net.minecraft.class_1761$class_7703.method_45417(class_1761.java:252) ~[client-intermediary.jar:?]
	at net.minecraft.class_1761$class_7704.method_45421(class_1761.java:286) ~[client-intermediary.jar:?]
	at org.valkyrienskies.eureka.registry.CreativeTabs.create$lambda$3(CreativeTabs.java:19) ~[eureka-1201-1.3.0-beta.3.jar:?]
	at me.shedaniel.rei.impl.client.fabric.CreativeModeTabCollectorImpl.collectTabs(CreativeModeTabCollectorImpl.java:56) ~[RoughlyEnoughItems-12.0.684-fabric.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at me.shedaniel.rei.plugin.client.DefaultClientPlugin.collectTabs(DefaultClientPlugin.java:174) ~[RoughlyEnoughItems-12.0.684-fabric.jar:?]
	at me.shedaniel.rei.plugin.client.DefaultClientPlugin.registerEntries(DefaultClientPlugin.java:135) ~[RoughlyEnoughItems-12.0.684-fabric.jar:?]
	at me.shedaniel.rei.impl.common.entry.type.EntryRegistryImpl.acceptPlugin(EntryRegistryImpl.java:69) ~[RoughlyEnoughItems-12.0.684-fabric.jar:?]
	at me.shedaniel.rei.impl.common.entry.type.EntryRegistryImpl.acceptPlugin(EntryRegistryImpl.java:51) ~[RoughlyEnoughItems-12.0.684-fabric.jar:?]
	at me.shedaniel.rei.api.common.registry.Reloadable.acceptPlugin(Reloadable.java:78) ~[RoughlyEnoughItems-12.0.684-fabric.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$startReload$9(PluginManagerImpl.java:417) ~[RoughlyEnoughItems-12.0.684-fabric.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$pluginSection$4(PluginManagerImpl.java:199) ~[RoughlyEnoughItems-12.0.684-fabric.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$startReload$10(PluginManagerImpl.java:407) ~[RoughlyEnoughItems-12.0.684-fabric.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.pluginSection(PluginManagerImpl.java:197) ~[RoughlyEnoughItems-12.0.684-fabric.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.startReload(PluginManagerImpl.java:405) ~[RoughlyEnoughItems-12.0.684-fabric.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCore._reloadPlugins(RoughlyEnoughItemsCore.java:162) ~[RoughlyEnoughItems-12.0.684-fabric.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$reloadPlugins$25(RoughlyEnoughItemsCoreClient.java:485) ~[RoughlyEnoughItems-12.0.684-fabric.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

So I would say it is safe to assume issue comes from Eureka or needs to be fixed on Eureka's end, keeping the issue open.

**Comment by sidlo01** [comment]
[Fabric 1.20.1] v1.3.0-beta.4 update fixed it for me

**Comment by GameBurrow** [comment]
Indeed, seems to be fixed by https://github.com/ValkyrienSkies/Eureka/commit/268540eb241029f34a3985e50b168a6940e03bbd
